apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: {{ .Values.frontend.label }}
    tier: frontend
spec:
  type: "{{ .Values.frontend.service.type }}"
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: 80
  selector:
    app: {{ .Values.frontend.label }}
    tier: frontend
