apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: helm-canary
      tier: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: helm-canary
        tier: frontend
        # {{- with .Values.frontend.labels }}
        # {{- toYaml . | nindent 8 }}
        # {{- end }}
    spec:
      containers:
      - name: helm-canary
        image: ghcr.io/mitchty/helm-canary:v0.0.4
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
        ports:
        - containerPort: 80
