apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    {{- with .Values.frontend.labels }}
    {{- toYaml . | nindent 4 }}
    tier: frontend
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 80
  selector:
    app: helm-canary
    tier: frontend
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
