name: Build and publish Docker image to ghcr.io
on:
  workflow_dispatch:

  # publish on releases, e.g. v2.1.13 (image tagged as "2.1.13" - "v" prefix is removed)
  release:
    types:
      - published

  # publish on pushes to the main branch (image tagged as "latest")
  push:
    branches:
      - master
      - main
    tags:
      - "v*.*.*"
    paths:
      - 'app/**'
      - Dockerfile
      - .github/workflows/release.yaml

env:
  TAG: ${{ github.ref_name == 'master' && 'latest' || github.ref_name }}

jobs:
  publish_ghcr_image:
    permissions:
      contents: read
      packages: write

    runs-on: "ubuntu-20.04"

    steps:
      - uses: actions/checkout@v2

      # https://github.com/marketplace/actions/push-to-ghcr
      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}  # it will be lowercased internally
          github_token: ${{ secrets.GITHUB_TOKEN }}
          image_tag:  ${{ env.TAG }}
